# Generated by Django 5.1.3 on 2024-12-01 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=255)),
                ('category1', models.CharField(max_length=50)),
                ('category2', models.CharField(blank=True, max_length=50, null=True)),
                ('category3', models.CharField(blank=True, max_length=50, null=True)),
                ('city_name', models.CharField(max_length=100)),
                ('district_name', models.CharField(blank=True, max_length=100, null=True)),
                ('subdistrict_name', models.CharField(blank=True, max_length=100, null=True)),
                ('village_name', models.CharField(blank=True, max_length=100, null=True)),
                ('street_name', models.CharField(blank=True, max_length=100, null=True)),
                ('building_number', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('operator', models.ForeignKey(limit_choices_to={'is_operator': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_parking', models.BooleanField(default=False)),
                ('paid_parking', models.BooleanField(default=False)),
                ('handicap_parking', models.BooleanField(default=False)),
                ('large_vehicle_parking', models.BooleanField(default=False)),
                ('entrance_fee', models.BooleanField(default=False)),
                ('handicap_access', models.BooleanField(default=False)),
                ('wheelchair_rental', models.BooleanField(default=False)),
                ('handicap_toilet', models.BooleanField(default=False)),
                ('guide_dog_allowed', models.BooleanField(default=False)),
                ('braille_guide', models.BooleanField(default=False)),
                ('audio_guide', models.BooleanField(default=False)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='facilities.facility')),
            ],
        ),
    ]
