# Generated by Django 5.1.3 on 2024-12-01 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('reservation_phone', models.CharField(max_length=15)),
                ('reservation_url', models.URLField(blank=True, null=True)),
                ('app_name', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_count', models.PositiveIntegerField(default=0)),
                ('operation_area_internal', models.CharField(blank=True, max_length=255, null=True)),
                ('operation_area_external', models.CharField(blank=True, max_length=255, null=True)),
                ('usage_restrictions', models.TextField(blank=True, null=True)),
                ('usage_fees', models.TextField(blank=True, null=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
